name: Devops Deploy.sh

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4.2.2
    - name: Copy SSH key
      run: |
          echo "${{ secrets.SSH_KEY }}" >> ./id_ed25519
          chmod 600 id_ed25519
    - name: Run deploy script
      run: |
          scp -C -o StrictHostKeyChecking=no -i ./id_ed25519 ./deployment/bin/deploy.sh ${{ secrets.SSH_CONNECTION_DIGITAL_OCEAN }}:/home/diego/deploy.sh
          scp -C -o StrictHostKeyChecking=no -i ./id_ed25519 ./id_ed25519 ${{ secrets.SSH_CONNECTION_DIGITAL_OCEAN }}:/home/diego/.ssh/id_ed25519
          ssh -tt -o StrictHostKeyChecking=no -i ./id_ed25519 ${{ secrets.SSH_CONNECTION_TESTING }} "chown root:root /home/diego/deploy.sh && chmod +x /home/diego/deploy.sh"
          ssh -tt -o StrictHostKeyChecking=no -i ./id_ed25519 ${{ secrets.SSH_CONNECTION_TESTING }} "/home/diego/deploy.sh ${{ secrets.MYSQL_PASSWORD }}"